services:
  - type: web
    name: 9M solutions-frontend
    env: static
    staticPublishPath: build

    headers:
      - path: /static/*
        name: Cache-Control
        value: public, max-age=31536000, immutable

      - path: /*.(png|jpg|jpeg|webp|avif|svg|woff|woff2)
        name: Cache-Control
        value: public, max-age=31536000, immutable

      - path: /
        name: Cache-Control
        value: no-cache
